"""Add discount fields to Product model

Revision ID: 017e694d9201
Revises: 84e9da14d5dd
Create Date: 2025-08-14 20:39:05.125572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017e694d9201'
down_revision = '84e9da14d5dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_discount', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('discount_percentage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('discount_percentage')
        batch_op.drop_column('has_discount')

    # ### end Alembic commands ###
