"""Simplified models with string fields instead of enums

Revision ID: 7101d0d316bf
Revises:
Create Date: 2025-08-17 22:15:12.820061

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = "7101d0d316bf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_category_name"), ["name"], unique=True)

    op.create_table(
        "color",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "hex_code", sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("color", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_color_name"), ["name"], unique=True)

    op.create_table(
        "customer",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("postal_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("province", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "address_reference", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("delivery_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "preferred_delivery_time", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_customer_email"), ["email"], unique=False)

    op.create_table(
        "paymentconfig",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("config_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("config_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("config_data", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("genero", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("estado", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("categoria", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("edad_destino", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_unique", sa.Boolean(), nullable=False),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("talle", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("stock", sa.Integer(), nullable=True),
        sa.Column("has_discount", sa.Boolean(), nullable=False),
        sa.Column("discount_percentage", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "role",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_role_name"), ["name"], unique=False)

    op.create_table(
        "size",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("numeric_size", sa.Integer(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("size", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_size_name"), ["name"], unique=True)

    op.create_table(
        "user",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("firebase_uid", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_user_firebase_uid"), ["firebase_uid"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    op.create_table(
        "inventory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("last_update", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("total", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column(
            "payment_method",
            sqlmodel.sql.sqltypes.AutoString(length=20),
            nullable=False,
        ),
        sa.Column(
            "payment_status",
            sqlmodel.sql.sqltypes.AutoString(length=20),
            nullable=False,
        ),
        sa.Column(
            "mercadopago_payment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "mercadopago_preference_id",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            "bank_account_info", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "transfer_receipt_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("transfer_verified", sa.Boolean(), nullable=True),
        sa.Column("transfer_verification_date", sa.DateTime(), nullable=True),
        sa.Column("delivery_cost", sa.Float(), nullable=True),
        sa.Column("delivery_zone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("delivery_scheduled_date", sa.DateTime(), nullable=True),
        sa.Column(
            "delivery_time_slot", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("delivery_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("delivery_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("admin_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("verification_required", sa.Boolean(), nullable=False),
        sa.Column("verified_by_admin", sa.Boolean(), nullable=True),
        sa.Column("admin_verification_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "productimage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "productvariant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("talle", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "userrole",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), nullable=False),
        sa.Column("assigned_by", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orderitem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orderitem")
    op.drop_table("userrole")
    op.drop_table("productvariant")
    op.drop_table("productimage")
    op.drop_table("order")
    op.drop_table("inventory")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))
        batch_op.drop_index(batch_op.f("ix_user_firebase_uid"))
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("user")
    with op.batch_alter_table("size", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_size_name"))

    op.drop_table("size")
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_role_name"))

    op.drop_table("role")
    op.drop_table("product")
    op.drop_table("paymentconfig")
    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_customer_email"))

    op.drop_table("customer")
    with op.batch_alter_table("color", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_color_name"))

    op.drop_table("color")
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_category_name"))

    op.drop_table("category")
    # ### end Alembic commands ###
