"""add product attributes color, talle, genero, estado, edad_destino

Revision ID: 9594ecb80a6d
Revises: 04994efbc2ce
Create Date: 2025-07-30 21:37:05.927042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9594ecb80a6d'
down_revision: Union[str, Sequence[str], None] = '04994efbc2ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('talle', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('genero', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('edad_destino', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('edad_destino')
        batch_op.drop_column('estado')
        batch_op.drop_column('genero')
        batch_op.drop_column('talle')
        batch_op.drop_column('color')
        batch_op.drop_column('color')

    # ### end Alembic commands ###
