"""Add shipping_status field to Order model

Revision ID: 964a84b05311
Revises: 9b177b8722fc
Create Date: 2025-08-31 22:13:52.073262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964a84b05311'
down_revision = '9b177b8722fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_status', sa.String(length=20), nullable=False, server_default='pending'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('shipping_status')

    # ### end Alembic commands ###
