"""Add delivery_method to orders and remove variant_id from order_items

Revision ID: 9ce16f121476
Revises: 5f8d2c39e1a4
Create Date: 2025-08-24 18:15:37.875456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ce16f121476'
down_revision = '5f8d2c39e1a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_method', sa.String(length=30), nullable=True))

    with op.batch_alter_table('orderitem', schema=None) as batch_op:
        batch_op.drop_constraint('orderitem_variant_id_fkey', type_='foreignkey')
        batch_op.drop_column('variant_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderitem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('orderitem_variant_id_fkey', 'productvariant', ['variant_id'], ['id'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('delivery_method')

    # ### end Alembic commands ###
