"""Initial
  migration with all tables

Revision ID: f45eddb8346a
Revises:
Create Date: 2025-08-16 01:08:00.448792

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f45eddb8346a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create ENUM types if they don't exist (PostgreSQL compatible)
    connection = op.get_bind()
    
    # Check and create roletype ENUM
    result = connection.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'roletype'"))
    if not result.fetchone():
        op.execute("CREATE TYPE roletype AS ENUM ('ADMIN', 'MANAGER', 'EMPLOYEE', 'USER')")
    
    # Check and create paymentmethod ENUM
    result = connection.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'paymentmethod'"))
    if not result.fetchone():
        op.execute("CREATE TYPE paymentmethod AS ENUM ('TRANSFER', 'MERCADOPAGO', 'CASH')")
    
    # Check and create paymentstatus ENUM
    result = connection.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = 'paymentstatus'"))
    if not result.fetchone():
        op.execute("CREATE TYPE paymentstatus AS ENUM ('PENDING', 'PENDING_PAYMENT', 'APPROVED', 'REJECTED', 'CANCELLED')")
    op.create_table(
        "category",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_category_name"), ["name"], unique=True)

    op.create_table(
        "color",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "hex_code", sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("color", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_color_name"), ["name"], unique=True)

    op.create_table(
        "customer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_customer_email"), ["email"], unique=False)

    op.create_table(
        "product",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("genero", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("estado", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("categoria", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("edad_destino", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_unique", sa.Boolean(), nullable=False),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("talle", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("stock", sa.Integer(), nullable=True),
        sa.Column("has_discount", sa.Boolean(), nullable=False),
        sa.Column("discount_percentage", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "role",
        sa.Column(
            "name",
            postgresql.ENUM("ADMIN", "MANAGER", "EMPLOYEE", "USER", name="roletype", create_type=False),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_role_name"), ["name"], unique=False)

    op.create_table(
        "size",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("numeric_size", sa.Integer(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("size", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_size_name"), ["name"], unique=True)

    op.create_table(
        "user",
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("firebase_uid", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("nombre", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_user_firebase_uid"), ["firebase_uid"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    op.create_table(
        "inventory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("last_update", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("total", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column(
            "payment_method",
            postgresql.ENUM("TRANSFER", "MERCADOPAGO", "CASH", name="paymentmethod", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "payment_status",
            postgresql.ENUM(
                "PENDING",
                "PENDING_PAYMENT",
                "APPROVED",
                "REJECTED",
                "CANCELLED",
                name="paymentstatus",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "mercadopago_payment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "mercadopago_preference_id",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "productimage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "productvariant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("talle", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "userrole",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), nullable=False),
        sa.Column("assigned_by", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orderitem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orderitem")
    op.drop_table("userrole")
    op.drop_table("productvariant")
    op.drop_table("productimage")
    op.drop_table("order")
    op.drop_table("inventory")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))
        batch_op.drop_index(batch_op.f("ix_user_firebase_uid"))
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("user")
    with op.batch_alter_table("size", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_size_name"))

    op.drop_table("size")
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_role_name"))

    op.drop_table("role")
    op.drop_table("product")
    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_customer_email"))

    op.drop_table("customer")
    with op.batch_alter_table("color", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_color_name"))

    op.drop_table("color")
    with op.batch_alter_table("category", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_category_name"))

    op.drop_table("category")
    
    # Drop ENUM types if they exist and are not referenced by other objects
    op.execute("DROP TYPE IF EXISTS paymentstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS paymentmethod CASCADE") 
    op.execute("DROP TYPE IF EXISTS roletype CASCADE")
    # ### end Alembic commands ###
